### ISSUE TITLE
run.sh is out of date

### ISSUE THREAD

**Issue by munnellg** [pippokill/tri#1]
Hey there!

Just a minor issue, but it took me a bit of time to figure out what was going on. The `run.sh` script tries to execute version 0.1 of the TemporalRandomIndexing jar file, but the version generated by maven is 0.6. Easy enough to fix, but Java didn't produce any error messages that pointed to the problem, so it took a while to figure out what was going on. Might be interesting if `run.sh` could be generated by `mvn package` to make sure it is always looking for the right target.

**Comment by pippokill** [comment]
Fixed without maven integration. I plan to integrate it in a further version of the code.
